### ISSUE TITLE
[FEATURE] [FRONTEND] Alert user to sign-up/sign-in

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#155]
A user that is not logged in, I would like to get an alert to sign-in/sign-up in order to track my progress

#### Tasks (where applicable)
- [x] Add an alert view if a user is unauthenticated

####  Tests (where applicable)
- [x]  test for the alert trigger when the user is not logged in
- [x] tests for no alert trigger when the user is logged in

#### Acceptance Criteria
- [x] When a user is not logged in, an alert to sign-in/sign-up appears at the top
