### ISSUE TITLE
[FEATURE] [BACKEND] user progress object for each request

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#157]
A front-end developer I want to receive user progress percentage base on the  status of each *category in wikonnect
*category = from courses to chapters

#### Tasks
Display progress on:
- [x]  courses
- [x]  modules
- [x]  lessons
- [ ]  chapters [marked as done]

#### Tests
- [x] test for presence of progress object in each category request

Evidence of done
 A percentile object in each category request based on user chapter completion
- [x] courses
- [x]  modules
- [x]  lessons
- [x]  chapters [marked as done]
