### ISSUE TITLE
[FEATURE] [FRONTEND] user permissions management

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#158]
As an Admin/Superuser I would like to view and manage user role permissions [add/remove/change]

### Tasks

- [x]  Fetch users permissions from backend
- [x]  List users on template with checkbox
- [ ]  Send delete request to backend with

### Tests
- [x] tests for changing user roles/permissions

### Acceptance Criteria
- [x] Admin Should see a list of all users
- [x] Admin Should be able to select single or multiple users
- [ ] Admin Should be able to delete all selected users
- [ ] Users should disappear from list once deleted
