### ISSUE TITLE
[FEATURE] [BACKEND] Related Seeds for lean testing

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#171]
### Describe the user story:
As a front end user, I would like to receive related data for display testing and user flow testing 

### Tasks (where applicable)
We need to have
- [ ]  4 courses
- [ ]  4 modules in each course
- [ ]  4 lessons in each module
- [ ]  2 chapters in each lesson

### Acceptance Criteria
- As a leaner, I would like to go through the wikonnect app from courses to chapters and see the content without any missing fields.
