### ISSUE TITLE
[FEATURE] [BACKEND] Learning paths for users

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#189]
### Describe the user story:

As a frontend user, I would like to query all learning paths and display them to the user

### Tasks (where applicable)

- [x] docs for learning path endpoint
- [ ] on every request return user permisisons object
- [x] update access control permissions to match the platform routes

### Tests (where applicable)

- [ ]  test correct user permissions booleans are being returned on every request
