### ISSUE TITLE
[FEATURE] [BACKEND] Extension of impact tracking dashboard

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#207]
### Describe the user story:

As Wikonnect we would like to monitor the collective impact  made through the platform
This requires tracking of specific data points as documented by the M&E team.
The collection can be done by a mix of online surveys and pre-collected data(e.g. completion rate of courses, most taken lesson...)

Further details can be found [here](https://docs.google.com/spreadsheets/d/0B58FLSwyzdApUzRpMUFicFdlSHByazZEWTY3MDFWUVo2amlz/edit#gid=1595611418) - access requests might be required

####  Expanded work plan for M&E
All this needs to answer the following questions:
- [x] Number of active content contributors in the platform
- [x]  Number of qualified content contributors in the platform
- [x] Total number of learning modules successfully completed
- [x] Number of learners (signups) that successfully enrol and complete at least 2 modules
- [x] Number of active software contributors to the platform
