### ISSUE TITLE
[FEATURE] [BACKEND] content creators permission infrastructure

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#208]
### Describe the user story:

As a frontend user accessing content creator routes, I would like to get a response based on the permission level that is given to me

### Tasks (where applicable)
- [x] give permissions to admin + super admin access levels
- [x] return a valid boolean permissions object based on the user's access level
- [x] manage viewing and storing draft and archived content including viewing of content that has no chapters

### Tests (where applicable)

- [x] test valid + invalid permissions

### Acceptance Criteria
A user with admin and super admin access level can create content on the platform
