### ISSUE TITLE
[FEATURE] [BACKEND] leaderboard

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#211]
### Tasks (where applicable)

- [x]  eg. Fetch users end point 

### Tests (where applicable)

- [ ]  eg. Passing Tests for x

### Acceptance Criteria

- [x] eg end-point  " api/users" should not list users  for non-admin users
- [x] eg end-point  " api/users" should list users for admin users
