### ISSUE TITLE
[FEATURE] [FRONTEND] CHAPTER UPLOAD

### ISSUE THREAD

**Issue by proverbial-ninja** [tunapanda/wikonnect#214]
### Describe the user story:

Teacher/content creatord should be able to upload , create, edit and delete h5p chapters

### Tasks (where applicable)

- [x]  Create  chapter details
- [x]  Edit  chapter details
- [x]  Upload h5p
- [ ]  Delete chapter

### Tests (where applicable)

- [ ]  Create chapter tests
- [x]  Edit  chapter test
- [ ]  Upload h5p test
- [ ]  Delete chapter test
