### ISSUE TITLE
[WIK-96] [FEATURE] [FRONTEND]. Reworking home page

### ISSUE THREAD

**Issue by proverbial-ninja** [tunapanda/wikonnect#234]
### Describe the user story:

Chapters should be easily accessible by users immediately on site landing .

### Expected Behavior

The landing page should be a list available published & approved chapters

### Current Behavior

The current landing page shows content that should be on **about** page

### Tasks (where applicable)
- [ ]  Move **landing** page content to **about** page
- [ ]  Move homepage content to landing page
- [ ]  Update previous home routes to point to homepage index route
- [ ] Update tests to reflect the new flow
- [ ]  Add tests for chapters on scroll pagination

### Screenshots where applicable
