### ISSUE TITLE
[FEATURE] [FRONTEND] PUBLIC PROFILE 

### ISSUE THREAD

**Issue by proverbial-ninja** [tunapanda/wikonnect#236]
### Describe the user story:

Users should see another users profile 
Public profile should have a list of created chapters

### Tasks (where applicable)

- [x]   route for public profile
- [ ]  listing chapters a user has created on public profile
- [ ]  List courses a user has created on public profile
- [ ]  show publicly available user details

### Tests (where applicable)

- [ ] Should show profile page
- [ ] Should list uploaded chapters

### Acceptance Criteria

- [ ] User Should see profile page
- [ ] Profile page should have a list of created chapters
