### ISSUE TITLE
[FEATURE] [BACKEND] Tag management and storage

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#237]
### Describe the user story:

As a front-end user I would like to be able to view and search content using tags based on the content creators options.

### Tasks (where applicable)
- [x] modify migrations file to include multiple tag field
- [x] store tags in elastic search for easy search and accessibility in search route
- [x] test storage, search and editing of tags by admin and/or content creator
- [x] test elastic search integration by searching/filtering content using tags

- [x] log anonymised search requests

**Comment by mosesokemwa** [comment]
@mosesokemwa I will update the technical documentation for the API and ping Kiki.
