### ISSUE TITLE
[FEATURE] [FRONTEND] SEARCH FRONT END

### ISSUE THREAD

**Issue by proverbial-ninja** [tunapanda/wikonnect#242]
### Tasks (where applicable)

- [x] Search result Component

- [x] Search route

- [x] Empty State Component

### Tests (where applicable)

- [x]  Search Result Test

### Acceptance Criteria

- [x] User should be able to search
