### ISSUE TITLE
[FEATURE] [FRONTEND] New users onboarding process

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#277]
### Describe the user story:

As a new user on the platform, I would like to receive Hazina moja points after or during the onboarding process(creating an account to finishing one user

### Tasks (where applicable)
- [x] Sign up (with Invite Code)
- [x] User takes learner M&E quiz - 3
- [x] User views learning content - 5
- [x] User completes interactive video (with quiz) about Wikonnect, and how to learn (view content) - 5
- [x] User gives feedback on learning experience (e.g. star rating) - 2
- [x] User requests features or improvements (aided by multiplier) - 5
- [x] User has been fully onboarded as a learner - bonus points, as an incentive to try out teaching! - 5

Total awarded point will be 25

### Acceptance Criteria

- [x] User is awarded all expected points
