### ISSUE TITLE
[FEATURE] [FRONTEND] Chapters approval

### ISSUE THREAD

**Issue by proverbial-ninja** [tunapanda/wikonnect#290]
### Describe the user story:
Admin should be able to approve single or multiple chapters so that it is easier to manage home page

### Tasks (where applicable)

- [x]   Fetch chapters from backend
- [x]   List chapters 
- [x]  Approve page
- [x] Preview button

### Tests (where applicable)

- [ ]  eg. Passing Tests for x

### Acceptance Criteria

- [ ] eg Admin Should see a list of all users
- [ ] eg Admin Should be able to select single or multiple users
- [ ] eg Admin Should be able to delete all selected users
- [ ] eg Users should disappear from list once deleted
