### ISSUE TITLE
[FEATURE] [FRONTEND] localization frontend

### ISSUE THREAD

**Issue by proverbial-ninja** [tunapanda/wikonnect#292]
### Describe the user story:
User should be able to select prefered  language in settings
User should be able to switch languages where available

### Tasks (where applicable)

- [x]  Add intl library
- [x]  Update strings on wikonnect
- [x]  get and save user locale settings
