### ISSUE TITLE
[FEATURE] [BACKEND] Course review

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#295]
### Describe the user story:

A frontend user should be able to review a courses using a reaction button and/or count button

### Tasks (where applicable)
- [x] Route used for storing user reaction count(thumbs up/down)
- [x] Add a joining reactions table to courses with userid, reaction, timestamp

### Tests (where applicable)

An authenticated user can
- [x] Gives thumbs up
- [x] Remove their review
- [x] Give thumbs down
