### ISSUE TITLE
[FEATURE] [FRONTEND] Learner Visual Enhancements

### ISSUE THREAD

**Issue by proverbial-ninja** [tunapanda/wikonnect#339]
### Describe the user story:

Learners front-end should match design specification

### Tasks (where applicable)

- [x] Private Profile Page

- [x] Public profile page

- [x] Single Chapter Page

- [x] Home Page

- [x] Login Page

- [x] Sign Up Page
