### ISSUE TITLE
[ENHANCEMENT] [BACKEND] Documentation

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#350]
### Describe the user story:

Update the documentation for easy usage of the project

### Tasks (where applicable)
- [ ] Project setup
- [ ] Access to admin a dashboards
- [ ] Setting up social auth
- [ ] Database setup[migrations, seeds]
- [ ] Middleware functions
- [ ] Utility functions
