### ISSUE TITLE
[FEATURE] [BACKEND] Like and dislike chapter feature

### ISSUE THREAD

**Issue by proverbial-ninja** [tunapanda/wikonnect#399]
### Describe the user story:

Users (front-end) should be able to create like and dislikes for chapters
Users (front-end) should be able to see likes and dislikes  counts for chapters
### Tasks (where applicable)

- [x]  Endpoint to create like and dislike
- [x]  Chapter object should return like/dislike count
- [x]  Chapter object should return “like status” whether the chapter has been liked/disliked
- [x]  Liking a chapter that has been disliked should remove the dislike from chapter and vice versa
- [x]  Documentation
