### ISSUE TITLE
[FEATURE] [FRONTEND] IFrame check authorization

### ISSUE THREAD

**Issue by proverbial-ninja** [tunapanda/wikonnect#491]
### Describe the user story:
3rd party consumer should be able to visualy know whether they are logged in to wikonnect or not
3rd party consumer should be prompted to login/signup to keep track of progress

### Tasks (where applicable)

- [ ]  Prompt for authorization if not logged in
- [ ]  Give a visual indication of whether user is logged in
- [ ] Maybe provide custom login process for embed content
