### ISSUE TITLE
[FEATURE] [BACKEND] Teach badges awards

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#513]
### Describe the user story:
A teacher should earn a badge(s) when creating content on the platform

### Tasks (where applicable)
- [ ] Generate badges when a teacher publishes 1, 3, 6, 10, 15+  chapters
- [ ] create a badge when 1, 3, 6, 10, 15+ more chapters are approved by an administrator
- [ ] Award badges for completed chapters. Criteria being 1, 3, 6, 10, 15+  chapters

### Tests (where applicable)

- [ ]  Do not create a badge when the criteria is not met
- [ ]  Create a badge when criteria is met by users

### Acceptance Criteria
- [ ] Provide a list of all badges in the achievements awards api
- [ ] change status of earned badges in the status object field
