### ISSUE TITLE
[FEATURE] [BACKEND] reactions(like & unlike) api

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#514]
### Describe the user story:

Provide CRUD endpoints to allow frontend to Create read update and delete Reactions

This is currently for the likes and dislikes but provides room for more reactions in future

## tasks

- [x] Create endpoint for reaction
- [x] Update endpoint for reaction
- [x] Delete endpoint for reaction
- [x] Chapter object should have reaction details of authenticated user if it exists
- [ ] Chapter object should have counts for each reaction
- [x] Documentation

 Requirements

## CRUD endpoints that have these field

```
{
    "reaction":"like|dislike|whatever", 
    "chapter":{chapter},
    "user":{logged in user}
}
```
On the chapter object ... add the reactions count
```
{
  "chapter": [
    {
      "id": "IdlxNr8AAFU",
      "lessonId": null,
      "name": "What is the Internet?",
      "slug": "what-is-the-internet",
      "description": "In this interactive video, we get to LEARN what the internet is and where it came from... right from someone who co-created the internet in the 1970s! You'll also find some ideas for games you can PLAY together!  \n\n",
      "status": "published",
      "creatorId": "IcW8hCaAAB4",
      "metadata": null,
      "createdAt": "2020-11-10T04:53:34.165Z",
      "updatedAt": "2020-11-10T04:56:46.016Z",
      "contentType": "false",
      "contentUri": "/uploads/h5p/IdlxNr8AAFU",
      "imageUrl": "uploads/chapters/zw9t4yCrF.jpg",
      "contentId": null,
      "approved": "true",
      "topics": null,
      "rating": null,
      "comment": [],
      "reactions":{
          "likes":310,
          "dislikes":2,
          "whatever":9,
          "current_user": "likes|dislikes|whatever"
      }
    }
  ]
}
```

**Comment by mosesokemwa** [comment]
@proverbial-ninja how it looks like on the chapter view
<img width="739" alt="Screenshot 2021-01-27 at 16 59 06" src="https://user-images.githubusercontent.com/13944912/106001526-1f004c80-60c1-11eb-9c2d-90b9912a157f.png">
