### ISSUE TITLE
[FEATURE] [FRONTEND] [WIK-53] Filter chapters by multiple tags 

### ISSUE THREAD

**Issue by proverbial-ninja** [tunapanda/wikonnect#518]
### Describe the user story:

User should be able to filter h5p chapters lessons with multiple tags. The design reference for the tasks is available [here](https://xd.adobe.com/view/64025315-acae-4cd6-9ac8-b8b4f3883189-3151/specs/)

### Tasks (where applicable)

- [x]  Match the main navbar components similar to the design
- [x]  Display available tags
- [x] Filter by multiple tags
- [ ] Implementing the tags filter drop-down and active count design 
- [ ]  Clear filters
- [ ]  Implementing chapter lesson details preview card design changes
