### ISSUE TITLE
[FEATURE] [FRONTEND] Add reactions component on homepage chapter card and single chapter view [WIK-61]

### ISSUE THREAD

**Issue by proverbial-ninja** [tunapanda/wikonnect#520]
### Describe the user story:
An authenticated user should be able to like, unlike, retract, or switch their existing reaction while on the single chapter page only.  The homepage chapter card and single chapter page views should display the correct respective reactions count.

### Tasks (where applicable)

- [x]  Visual layout for Reaction component (Like & dislike buttons) 
- [ ] Reactions buttons should not be interactive at the homepage or if unauthenticated
- [ ] User new chapter reaction while on single chapter page should trigger reaction POST API request
- [ ] Retracting chapter reaction while on single chapter page should trigger reaction DELETE API request
- [ ] Switching chapter reaction while on single chapter page should trigger reaction PUT API request

### Tests (where applicable)

- [ ]  Reaction component is visible at homepage chapter card view
- [ ]  Reaction component is visible at single chapter page view
- [ ] Authenticated and non-authenticated user cannot react at the homepage level
- [ ] Only authenticated user can like, dislike, or retract chapter reaction
- [ ] Reaction count reflects correctly after user reaction component action

### Acceptance Criteria
- [ ] User should see reaction component at homepage chapter card and single chapter content page.
- [ ] User should only react at single chapter content page level.
- [ ] User new like or dislike should increment previous reaction count respectively.
- [ ] User should be able to retract their reaction.
- [ ] Retracted like/dislike should decrement the respective reaction count.
- [ ] User should be able to switch their current reaction
- [ ] Switching current reaction should increment current choice and decrement the previous choice.
