### ISSUE TITLE
[FEATURE] [FRONTEND] Posting user chapter view count [WIK-66]

### ISSUE THREAD

**Issue by proverbial-ninja** [tunapanda/wikonnect#525]
### Describe the user story:

When a user completes watching H5P chapter content, post anonymised views count to the backend.

### Tasks (where applicable)

- [x]  Add  completed interactive video [xAPI event listener](https://h5p.org/node/617/xapi-coverage) on H5P player 

### Tests (where applicable)

- [x]  View count is posted to the backend API  when user completes an interactive video

### Acceptance Criteria

- [x] A view count should be posted through API once a user completes watching an interactive video
