### ISSUE TITLE
[FEATURE] [BACKEND] [WIK-40] User object does not return user roles

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#556]
### Describe the user story:

User object needs to have user roles attached for managing users access to secured pages

### Tasks (where applicable)

- [x] For every login the users role is attached to the object
- [x] Update api documentation with the user role
- [x] User eager query to add the user role object and custom function for the object type

### Tests (where applicable)

- [x] User can still perform the tasks assigned to the role
- [x] No deletion can be done by non admin users
