### ISSUE TITLE
[FEATURE] [FRONTEND] [WIK-52] Fix CircleCi Ember Handlebars lint command and Ember lint issues

### ISSUE THREAD

**Issue by 0xMurage** [tunapanda/wikonnect#567]
### Describe the user story:
CircleCi Ember Handlebars lint command lints the JavaScript files. The commands misses existing lint issues.

### Tasks (where applicable)
- [x]  Fix CircleCi Ember lint command
- [ ]  Fix existing Ember Handlebars lint issues

### Tests (where applicable)
- [ ]  Passing lint test for Ember Handlebars
