### ISSUE TITLE
[WIK-57] [FEATURE] [FRONTEND] Add login and signup tests

### ISSUE THREAD

**Issue by 0xMurage** [tunapanda/wikonnect#577]
### Tasks (where applicable)
- [ ]  Add user form signup  tests
- [ ] Add user form sign in tests

### Tests (where applicable)

- [ ]  New user can register
- [ ] Existing user cannot register
- [ ] User cannot sign in without valid credentials
- [ ] User with valid credentials can sign in

### Acceptance Criteria

- [ ] Passing of all login tests pass scenarios
- [ ] Passing of all signup test scenarios
