### ISSUE TITLE
[FEATURE][FRONTEND] Single Chapter card on homepage should provide more details [WIK-59]

### ISSUE THREAD

**Issue by brianmarete** [tunapanda/wikonnect#586]
### Describe the user story:
The current chapter card shows a thumbnail, title, and description. This should be updated to match the new designs which provide more details to users.

### Tasks (where applicable)
In addition to thumbnail, title, and description, the new chapter card should show:
- [ ] View count
- [ ] How long ago it was created
- [ ] Reactions count
- [ ] Avatar of chapter's creator
- [ ] Link to share

### Tests (where applicable)

- [ ] View count should be visible
- [ ] Creation time should be visible
- [ ] Reaction count should be visible
- [ ] Sharing link should be visible
- [ ] Creator avatar should be visible

### Acceptance Criteria
Chapter card on homepage should match current designs
