### ISSUE TITLE
[FEATURE] [BACKEND] Verified badge to chapters object [WIK-62]

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#587]
### Describe the user story:

Front user should be able to display a verified badge based on the boolean status of a verified object in chapters query
### Tasks (where applicable)

- [x] Server migrations for adding a verified object in the chapters table
- [x] Update docs with the new chapter json response
- [ ] Verified status can only be changed using this flow  ``published -> approved -> verified``
- [ ] Only content approvers(admin, superadmin) can verify content

### Tests (where applicable)

- [ ] Updating verified status: Passes for admin and supersuers, fails for basic users
- [ ] Can only update after publishing and approval status changes

### Acceptance Criteria

- [ ] GET ``v1/api/chapters`` and ``v1/api/chapters/:id`` contains a verified boolean object
- [ ] POST ``v1/api/chapters`` defaults to a preset verified and approval object in the body data
- [ ] PUT ``v1/api/chapters`` strict update flow ``published -> approved -> verified``

```json
"chapter":{
    "id":"chapter1",
    "verified": "True"
}
```

```json
"chapter":{
    "id":"chapter1",
    "verified": "False"
}
```
