### ISSUE TITLE
[FEATURE] [FRONTEND] Update single chapter page to match designs [WIK-59]

### ISSUE THREAD

**Issue by 0xMurage** [tunapanda/wikonnect#588]
### Describe the user story:

The single chapter content details page should match the current designs.

### Tasks (where applicable)

- [ ]  Add reactions buttons below the H5P content view
- [ ]  Add share button aligned with reactions button
- [ ]  Add chapter sharing method
- [ ] Add vertical menu actions aligned with share button.
- [ ] Add chapter key information tab
- [ ] Add comments tab.

### Tests (where applicable)

- [ ] Reactions buttons should be visible
- [ ] Share buttons should be visible.
- [ ] User should be able to share a chapter
- [ ] User should be able to navigate to and view chapter key information
- [ ] User should be able to navigate to and view existing chapter comments

### Acceptance Criteria

- [ ] Chapter content details page matches the current designs.
