### ISSUE TITLE
[FEATURE] [BACKEND]Include name and profile pic to chapter object using creatorId(s) [WIK-80]

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#589]
### Describe the user story:

Frontend should be able to show the  content creator and profile picture on the chapters card

### Tasks (where applicable)

- [x] Models query options
- Relation mappings using``creatorId`` in chapter -> One to Many
- Eager query modifier in``users`` for ``chapters`` relation mappings
- [x] Check for privacy settings in users details

### Tests (where applicable)

- [x]  Contains user data (``profile pic,  username``) is included in the response object for chapter query

### Acceptance Criteria
- [x]  GET ``v1/api/chapters`` and ``v1/api/chapters/:id`` contains user data (``profile pic,  username``) in the API response chapter query

```json
"creatorId": "user1",
"author": {
    "username": "user1",
    "profileUri": null,
    "lastSeen": "2021-03-06T22:03:25.002Z"
}
```
### Screenshots where applicable

![Screenshot 2021-02-18 at 12 36 13](https://user-images.githubusercontent.com/13944912/108338995-efd48b00-71e7-11eb-8199-4c2d8a25bc43.png)
