### ISSUE TITLE
[FEATURE] [BACKEND] Reduce data loading redundancies using updated ORM function [WIK-78]

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#591]
### Describe the user story:

A frontend user can get eager data with ``type`` attribute in each object

#### Tasks (where applicable)

- [ ]  Add virtual attributes to models files
- [ ] Remove looping through eager data reducing the data load time

#### Tests (where applicable)

- [ ]  All test pass as they are

#### Example of chapter comments eager data
- Add below code to comments models
```JS
static get virtualAttributes() {
    return ['type'];
  }

  type() {
    return '<model_name>';
  }
```
- Delete the below code
```JS
async function returnType(parent) {
  if (parent.length == undefined) {
    parent.comment.forEach(comment => {
      return comment.type = 'comment';
    });
  } else {
    parent.forEach(mod => {
      mod.comment.forEach(comment => {
        return comment.type = 'comment';
      });
    });
  }
}
```
