### ISSUE TITLE
[FEATURE] [FRONTEND] Nested chapter comments [WIK-68]

### ISSUE THREAD

**Issue by 0xMurage** [tunapanda/wikonnect#592]
### Describe the user story:
Authenticated users should be able to comment on a chapter and reply to an existing level 1 comment.
### Tasks (where applicable)

- [x] Multi-level chapter comments design layout implementation
- [x] Chapter level 1 comments submission
- [x] User level 1 comment reply
- [ ] #774

### Tests (where applicable)

- [x]  Authenticated user can comment on a chapter
- [x]  Authenticated user can reply to an existing level 1 comment

### Acceptance Criteria
- [x] Only authenticated user should be able to comment on a chapter
- [x] User can reply to a level 1 chapter comment
- [x]  Only authenticated user can reply
- [ ] Comments component lazily loads paginated chapter comments

**Comment by 0xMurage** [comment]
I request to be assigned this issue

**Comment by brianmarete** [comment]
Moved the pagination/lazy loading to a separate issue
