### ISSUE TITLE
 [FEATURE] [BACKEND] Comment feature with reply [WIK-69]

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#593]
### Describe the user story:

A user can comment and another can reply on the same comment

### Tasks (where applicable)

- [ ] Join comment based on lookup tables with parent and child id references
- [ ] Modify database for new commenting structure
- Add lookup table for comment
- Two approaches
    - Relationship mapping from comment.id -> (parent.id, child.id) -> comment.id (sounds recursive)
    - add ``parent_id`` object  to comments for referencing when replying to a comment(sounds easy on paper, complexity might increase on implementation)
- [ ] Use [withGraphFetched](https://vincit.github.io/objection.js/api/query-builder/eager-methods.html#withgraphfetched) allowing for comments with replies

### Tests (where applicable)

- [ ] A user can create a comment
- [ ] A user can reply to a comment
- [ ] A user cannot reply to a replied comment

### Acceptance Criteria

- [ ] GET ``v1/api/comments`` and ``v1/api/comments/:id`` returns comments
- [ ] POST ``v1/api/comments`` creates a comment with and without a reply

### References
- An example implementation for Koa can be found [here](https://github.com/Vincit/objection.js/tree/master/examples/koa)
