### ISSUE TITLE
[FEATURE] [BACKEND] Dockerize Wikonnect [WIK-72]

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#594]
### Describe the user story:
As a developer, I would like a dockerized application for streamlined deployments.

### Tasks (where applicable)

- [x] Docker containers for: frontend/static/nginx, API, database, elastic-search, redis(?)
- [x] Docker compose to get it all working
- [x] Dockerfile for each service
- [x] Potentially use [``wait-for``](https://github.com/Eficode/wait-for) to control startup and shutdown order in Compose

### Resources
- [The Docker Handbook](https://www.freecodecamp.org/news/the-docker-handbook/#introduction-to-containerization-and-docker)
- [Docker compose docs](https://docs.docker.com/compose/)
- [Getting started with Django](https://docs.docker.com/compose/django/) for people familiar with Django
- [Video on Dockerization of NodeJS, Redis and Postgres](https://www.youtube.com/watch?v=aetqo2nkQcA)
- [Recommended tools in Docker](https://docs.docker.com/compose/startup-order/)
