### ISSUE TITLE
[WIK-82] [FEATURE] [FRONTEND] Upgrading Ember to the latest LTS version

### ISSUE THREAD

**Issue by 0xMurage** [tunapanda/wikonnect#606]
### Describe the user story:
To ensure the Wikonnect builders enjoy latest Ember features and improve their productivity, the frontend app requires upgrading to Octane; specifically an LTS version (*the latest currently is 3.24)
### Tasks (where applicable)
- [ ] Resolve deprecated and update code patterns in:
    - [ ] Landing page
    - [ ] Sign up & login pages
    - [ ] Homepage
    - [ ] Single chapter view page
    - [ ] Search results page
    - [ ] User profile page
    - [ ] Teach layout page

- [ ] Update project Ember CLI & Ember core dependencies 
- [ ] Resolve any major conflicts

### Tests (where applicable)

- [ ]  All existing tests pass

### Acceptance Criteria

- [ ] Passing of all existing feature tests
- [ ] Project utilizing latest LTS Ember Octane
