### ISSUE TITLE
[WIK-86] [FEATURE] [Backend] H5P content migration

### ISSUE THREAD

**Issue by 0xMurage** [tunapanda/wikonnect#629]
### Describe the user story:

System users should be able to access their previously uploaded H5P content with the Wikonnect integrated H5P editor.

### Tasks (where applicable)

- [ ]  Create and run script to transform existing H5P content structure into a format compatible with current setup
- [ ]  Remove `contentUri` property on a chapter
- [ ]  Delete the old H5P content.

### Tests (where applicable)

- [ ]  TBD

### Acceptance Criteria

- [ ] All H5P content should be available through `/api/v1/h5p` endpoints
- [ ] User's should be able to update H5P content through the system integrated H5P editor
