### ISSUE TITLE
[WIK-74] [FEATURE] [BACKEND] Wikonnect submission as an oEmbed provider

### ISSUE THREAD

**Issue by 0xMurage** [tunapanda/wikonnect#634]
### Describe the user story:
To enable Wikonnect to captivate a greater audience, existing & new content should be easy to embed on third-party sites. Additionally, Wikonnect should be discoverable as an oEmbed rich media provider to any interested consumer.

### Tasks (where applicable)

- [x]  Ensure the embed API endpoint response conforms with oEmbed format. 
- [x]  Add referrer to the HTML iframe  embed endpoint response property
- [x] Inject oEmbed content headers on each chapter page
- [ ] Ensure the content is crawlable.
- [ ] Request to be Embedly Provider [here](https://embed.ly/providers/form)
- [ ] Create pull request to be a provider [here](https://github.com/iamcal/oembed)

### Tests (where applicable)

- [x]  Passing of oEmbed endpoint on [Embed.ly ](https://embed.ly/providers/validate/oembed) page
- [x] oEmbed headers automatically and correctly injected on each chapter page

### Acceptance Criteria

- [x] `/api/v1/oembed` should return valid oEmbed response on error and on success

**Comment by brianmarete** [comment]
@mimidotsuser Has this issue been resolved?

**Comment by 0xMurage** [comment]
@brianmarete I have checked off the completed tasks.
Submission as an oEmbed provider via Embed.ly was not done since the platform content is not crawlable at the moment. ( as per [Embed.ly Requirements](https://embed.ly/providers/new) ) 
Crawling of the content was to be done under the Fastboot ticket. The ticket was shelved to address other higher-priority tickets.
