### ISSUE TITLE
[FEATURE] [BACKEND] Password reset [WIK-100]

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#638]
### Describe the user story:
A front end user should be able to integrate password reset process with the backend apis

### Tasks (where applicable)

- [ ] Validate email and/or phone numbers for password reset request
- [ ] Set 1hr expiry time for a password reset token
- [ ] Send an email with a password reset token
- [ ] Send email notification for a successful password reset
- [ ] Update password api

### Tests (where applicable)

- [ ] Validate password reset token expiry time
- [ ] Email sending
- [ ] User password reset using token

```JS
const tokenSchema ={
  userId: {
    type: Schema.Types.ObjectId,
    required: true,
    ref: "user.id",
  },
  token: {
    type: String,
    required: true,
  },
  createdAt: {
    type: Date,
    default: Date.now,
    expires: 3600
  }
}
```
