### ISSUE TITLE
[FEATURE] [BACKEND] Email Verification [WIK-98]

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#639]
### Describe the user story:

On signup, a user should receive an email to verify their email

### Tasks (where applicable)

- [ ] On signup send email with verification token
- [ ] Update email verification status to ``tue``

### Tests (where applicable)

- [ ] Email verification token expiry time
- [ ] Send email on user creation
- [ ] Update valid email address

### Acceptance Criteria

- [ ] eg end-point  " api/users" should not list users  for non-admin users
- [ ] eg end-point  " api/users" should list users for admin users
