### ISSUE TITLE
[FEATURE] [BACKEND] Additional login options (Twitter & Facebook & Github)

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#642]
### Describe the user story:

Provide additional login option using Twitter, Facebook and GitHub

### Tasks (where applicable)
- [x] Api for creating user using Github, Twitter, Facebook
- [x] Create usernames using the above details on scope(email, fullname)

### Acceptance Criteria

- [x]  Users can login using twitter, Github and facebook

### Resources
- Designs by [Yego](https://xd.adobe.com/view/c8cdd600-0ec7-4557-a497-7bcf80177a5e-9d9e/screen/81e6e050-d1bc-4311-be39-515c9fa11047)
