### ISSUE TITLE
[FEATURE] [FRONTEND] Additional Auth Frontend Login / signup pages 

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#643]
### Describe the user story:

A user can log in using additional login option(Twitter, Facebook and GitHub)

### Tasks (where applicable)

- [ ] Login/Signup buttons
- [ ] Components for the additional option where necessary

### Acceptance Criteria

- [ ] User can login using the additional login options

### Resources
- [ ] Designs by [Yego](https://xd.adobe.com/view/c8cdd600-0ec7-4557-a497-7bcf80177a5e-9d9e/screen/81e6e050-d1bc-4311-be39-515c9fa11047)
