### ISSUE TITLE
[FEATURE] [BACKEND] Password reset email templates

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#644]
### Describe the user story:

A user gets an email with password reset details 

### Tasks (where applicable)

Create templates for
- [x] Password reset
- [x] Creation of new account
- [ ] #816
- [ ] Send above email when related activity is completed

### Tests (where applicable)

- [ ]  Can send emails

**Comment by brianmarete** [comment]
@mosesokemwa What details should be included in the weekly/monthly achievement breakdown email? Check under tasks
