### ISSUE TITLE
[FEATURE] [BACKEND] Profanity check on chapter reviews, user bios

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#645]
### Describe the user story:

Check for profane language in user bios and chapter reviews

### Tasks (where applicable)

- [ ] Check for profane context in chapter reviews and user bios
- [ ] Extend the current library with more complex words and comments

### Tests (where applicable)

- [ ]  User bios and chapter reviews will not allow porfane data
