### ISSUE TITLE
[WIK-99] [FEATURE] [FRONTEND] Alerts & Notifications

### ISSUE THREAD

**Issue by brianmarete** [tunapanda/wikonnect#646]
### Describe the user story:
As a user I'd like to subscribe to notifications on updates and uploads by an author/tag so that I can stay up to date on new content. 

### Tasks (where applicable)
- [x] Add notifications icon on menu bar where user can see new notifications
- [x] Add section in user profile where user can set the tags they would like to see notifications on
- [ ] Add bell icon next to author's avatar in single chapter page where user can click to subscribe

### Tests (where applicable)

- [ ] Creating new chapter sends to notification to users subscribed to author
- [ ] Creating new chapter sends to notification to users subscribed to tag 

### Acceptance Criteria
A user is able to subscribe to notifications on updates and uploads to by an author. 
User is able to subscribe to notifications for chosen tags.
