### ISSUE TITLE
[FEATURE] [FRONTEND] Provide a way for a user to delete their chapter comments & replies

### ISSUE THREAD

**Issue by 0xMurage** [tunapanda/wikonnect#674]
### Describe the user story:
A learner should be able to delete their existing chapter comment or reply.

### Tasks (where applicable)

- [ ]  Add an action on each comment to enable user to initiate delete action
- [ ]  Add an action on each reply to enable user to initiate delete action  
- [ ]  Send delete request to backend API

### Tests (where applicable)

- [ ]  User can delete their own comment
- [ ] User can delete their reply
- [ ] User cannot delete other user's comment
- [ ] User cannot delete other user's reply

### Acceptance Criteria

- [ ] Learner should be able to delete their chapter comment or reply
