### ISSUE TITLE
[FEATURE] [FRONTEND] Increment chapter view count only if user has engaged with the H5P content

### ISSUE THREAD

**Issue by 0xMurage** [tunapanda/wikonnect#675]
### Describe the user story:
The number of chapter views should be posted to the backend only if the user has started engaging with the content through the H5P player.

### Tasks (where applicable)

- [ ] Listen to interaction xAPI event emitted by the player at an appropriate time depending on the content type. Reference available [here](https://h5p.org/documentation/x-api)
- [ ] Post view count only if the identified statement (above) is emitted by the player

### Acceptance Criteria
- [ ] View count doesn't increment when a user (only) visits the chapter page without interacting with chapter H5P content

**Comment by mosesokemwa** [comment]
Currently we have 3 triggers for a counter
- On page load of a chapter page
- Spent at least 10-30secs a chapter page
- And lastly, if the chapter is completed

The final view count the user see's is based on the 2nd trigger, and the other two we need for analytics.

How does this ticket seek to improve the above?

@mimidotsuser

**Comment by 0xMurage** [comment]
@mosesokemwa this ticket seeks to ensure the user plays the content before we count it as a view. Spending some seconds on the page usually doesn't translate to the user having started viewing the H5P content

**Comment by mosesokemwa** [comment]
Wasn't clear in ticket what changes you were planning on making. I agree that a timer does not necessarily represent a correct page view
