### ISSUE TITLE
[FEATURE] [FRONTEND] H5P player(s) should show loading feedback during initialization

### ISSUE THREAD

**Issue by 0xMurage** [tunapanda/wikonnect#676]
### Describe the user story:
When the H5P player is loading the content to play, a progress loader should be shown until everything is loaded successfully or an error is encountered. Meaningful feedback should be shown to the user if an error is experienced.

### Tasks (where applicable)
- [ ]  Implement H5P player initialization loader
- [ ]  Replace the above loading feedback once the H5P player emits the first `attempted` xAPI event statement or when an error is encountered

### Tests (where applicable)

- [ ]  T.B.D

### Acceptance Criteria

- [ ] H5P player initialization feedback is shown until content is loaded successfully or an error is encountered
- [ ] H5P initialization error feedback is shown to the user if an error is encountered
