### ISSUE TITLE
[FEATURE] [FRONTEND] Badge management

### ISSUE THREAD

**Issue by 0xMurage** [tunapanda/wikonnect#681]
### Describe the user story:

As an admin, I should be able to create, update, delete and view all available badges

### Tasks (where applicable)

- [x]  Add view & logic for an admin to create a new badge
- [x]  Fetch & list available badges from backend 
- [x]  Add logic to enable deleting of existing badges
- [x]  Add logic to enable admin to update badge details
- [ ]  Add view & logic to enable admin see all users who have earned a badge
- [ ] Add logic to enable admin revoke a badge earned by a user

### Tests (where applicable)

- [ ] A user can create a badge
- [ ] A user can update a badge
- [ ] A user can delete a badge
- [ ] A user can view users who have earned a badge
- [ ] A user can revoke a badge issued to a user
- [ ] The above user is an admin ***(applicable with the availability of user management module)

### Acceptance Criteria

- [ ]  Admin should see a list of all badges
- [ ] Admin should see a list of users who have a badge
- [ ] Admin should update or delete available badges
- [ ] Admin should be able to revoke a badge
