### ISSUE TITLE
[FEATURE] [FRONTEND] Gamification badge leaderboard 

### ISSUE THREAD

**Issue by 0xMurage** [tunapanda/wikonnect#682]
### Describe the user story:
As a user, I should be able to publish earned badges for public sharing. Published badges should also appear on a Wikonnect leaderboard.
 
### Tasks (where applicable)

- [ ]  Fetch and list user's earned badges on a private page
- [ ]  Add logic for a user to publish badges so they can be shared with the public
- [ ] Add a public achievements view that lists individual publicly shared badges.
- [x]  Add a view and logic for Wikonnect  leaderboard  (public badges only)
- [ ]  Notify a user when they earn a badge*

### Tests (where applicable)

- [ ] User can view all their earned badges on a private page
- [ ] Only published for share badges are available publicly
- [ ] Only publicly shared badges are shown on Wikonnect leaderboard
- [ ] Visual indicator is shown once they earn a badge *

### Acceptance Criteria
- [ ] A leaderboard that lists people with the most points and what badges
- [ ] Earned badges should be private until the user decides to share with the public
- [ ] Users can publish their badges to be available publicly

**Comment by brianmarete** [comment]
This is being worked on in [this](https://github.com/tunapanda/wikonnect/tree/feat/badges-and-leaderboard) branch
