### ISSUE TITLE
[FEATURE] [BACKEND][WIK-109] Provision of user management by moderators and admins

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#696]
### Describe the user story:

A frontend moderator, admin and super admin can view and/or alter user information using preset functions on the admin dashboard.

### Tasks (where applicable)

- [x]  Flagging user endpoint under already user routes
- [x]  Change properties under userRoles in user object from ``name, type`` to ``id, type``
- [x]  Change ``server/route/admin.js`` file to to ``server/route/userRoles.js``
- [x]  Assign roles(userRoles routes)
    - [x]  Documentation on changing and assignment of roles
    - [x]  Change permissions to
        - Basic = Learner
        - Teacher = Teacher
        - Moderator = Moderator
        - Admin
        - SuperAdmin

### Tests (where applicable)

- [x] Moderators can modify a users role
- [x] A Moderator can flag a user for review by Admin
- [x] User object always contains user_roles with id and type properties
- [x] Only Moderators, admin and super admin can modify a user's permission
