### ISSUE TITLE
[FEATURE] [BACKEND] Badges API

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#708]
### Describe the user story:
As a frontend admin user, I should be able to create, update, delete and view all available badges

#### Tasks (where applicable)
 - [x] Create new badges
 - [x]  Fetch & list available badges
 - [x] Deletion of existing badges
 - [x] Update badge details
 - [ ] Query all users who have earned a badge
 
#### Admin user can;
- [x] Create a badge
- [x] Update a badge
- [x] Soft-delete a badge
- [ ] View all users who have earned badges
- [ ] Revoke a badge issued to a user
