### ISSUE TITLE
[FEATURE] [FRONTEND] User public & private profile view

### ISSUE THREAD

**Issue by 0xMurage** [tunapanda/wikonnect#729]
### Describe the user story:
Any Wikonnect should be able to see user profile page which lists:
- User basic info (name, role,bio, and location if shared)
- Total chapters created & completed by user  
- Total points the user have earned ~ aggregate of badges total points
- Badges the user have unlocked and are available for general public
-
The account profile owner should be able to:
- edit their basic info. 
- share an individual badge
- modify unlocked badge public availability status
- 
### Tasks (where applicable)
- [x]  Modify current profile page to be available publicly
- [x] Add user basic info card section
- [ ] Add user's unlocked badges, total points accumulated, and chapters created + completed sections,
- [x] Add user profile edit page 

### Tests (where applicable)
-  [x]  User A can view user's B profile
-  [x]  Anonymous users can view available user profile
-  [x] Only account profile owner can update respective details

### Acceptance Criteria
-  [x]  Anonymous users & user A can view user's B profile
