### ISSUE TITLE
[FEATURE] [FRONTEND] Provide a way for a user to edit their chapter comments and replies

### ISSUE THREAD

**Issue by brianmarete** [tunapanda/wikonnect#787]
### Describe the user story:
As a user, I would like to be able to edit a comment or reply that I've made to a chapter so that I can have a way to correct my comment if I made a mistake

### Tasks (where applicable)

- [ ]  Add an action on each comment to enable user to initiate edit action
- [ ]  Add an action on each reply to enable user to initiate edit action
- [ ]  Once a comment has been edited, signify that it has been edited 
- [ ]  Send delete request to backend API

### Tests (where applicable)

- [ ]  A comment/reply shows it has been edited
- [ ]  User can edit their own comment
- [ ]  User can edit their reply
- [ ]  User cannot edit other user's comment
- [ ]  User cannot edit other user's reply

### Acceptance Criteria

- [ ] User should be able to delete their chapter comment or reply
- [ ] Comment shows it has been edited if edited
