### ISSUE TITLE
[FEATURE] Banner upload endpoint

### ISSUE THREAD

**Issue by proverbial-ninja** [tunapanda/wikonnect#89]
As a content creator, I would like to upload an image for new courses, modules and lessons when creating  content

#### Tasks
- [x] update database table to include a banner image URI
- [x] save images in a specific AWS S3 bucket
- [x] update the documentation to include the upload fields object in courses, module and lesson request object
- [x] add documentation on uploading images in each sub category
- [x] test upload functionality
