### ISSUE TITLE
[FEATURE] [FRONTEND] [WIK-46] Posting a lesson comment should immediately update and give user feedback.

### ISSUE THREAD

**Issue by mosesokemwa** [tunapanda/wikonnect#91]
### Describe the user story:
User should be able to leave a comment on a lesson that should be visible on comment section component immediately after successful posting. 

### Tasks (where applicable)
- [x] lesson comment component
- [ ] update the comment section automatically after posting
- [ ] system feedback on process success or error
- [ ] preserve posted comments line breaks

### Tests (where applicable)
- [ ] user can post a comment
- [ ] system feedback visible on process success or error
- [ ] posted comment visible immediately without page reload

**Comment by Aduda-Boaz** [comment]
I would love to work on this....
